version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./web:/var/www/html
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./web:/var/www/html
      - ./log_cerbot:/var/log/letsencrypt/
    depends_on:
      - nginx
    command: certonly -v --webroot --webroot-path=/var/www/html --email tatyanakuscheva@gmail.com --agree-tos --no-eff-email -d examplefortest.pp.ua
    networks:
      - app-network

networks:
  app-network:
    driver: bridge